WIP: Entity framework set up
Demestrus/BrimScheduleApp pull request #3
Opened 2021-02-05 21:34 UTC by Silurus

2021-02-13 21:16 UTC, Silurus commented on backend/BrimSchedule.API/Startup.cs
> +				app.UseHttpsRedirection();
Перенес эту штуку в прод-конфигурацию, т.к. она надоедливо перенаправляет на https, когда дебажишь на локальной машине

2021-02-13 21:16 UTC, Silurus commented on backend/BrimSchedule.API/Startup.cs
> +			dbContext.Database.Migrate();
Для автоматических миграций EF

2021-02-13 21:16 UTC, Silurus commented on backend/BrimSchedule.API/Startup.cs
> +			services.ConfigureDependencyInjection(CurrentEnvironment.IsDevelopment(), Configuration);
Сделал extension-класс, чтобы прописывать все DI конфигурации там

2021-02-13 21:35 UTC, Silurus commented on backend/BrimSchedule.API/Program.cs
> +				.UseDefaultServiceProvider(options => options.ValidateScopes = false) // for EF core
У меня EF ругался, когда я пытался настроить миграции в Startup классе

2021-02-17 11:59 UTC, Demestrus requested changes

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.API/Startup.cs
> +			dbContext.Database.Migrate();
Мне кажется в Configure не совсем место для накатывания миграций.

В официальных [how-to](https://docs.microsoft.com/ru-ru/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli) от microsoft предлагают делать это в методе Main класса Program:
```charp
public static void Main(string[] args)
{
	var host = CreateHostBuilder(args).Build();
	using (var scope = host.Services.CreateScope())
	{
		var db = scope.ServiceProvider.GetRequiredService<BrimScheduleContext>();
		db.Database.Migrate();
	}
	host.Run();
}
```

Правда, рекомендуют применять с осторожностью из-за возможных проблем. Так как у нас приложушка и базенка небольшая, думаю пока такой вариант нас должен устроить. 

Почему лучше в Main накатывать: если миграция не применится, вылетит эксепшн и приложенька не взлетит. В Configure, тем более в конце метода, скорее всего если эксепшн вылетит, а приложенька запуститс и схема БД будет некорректной - получим ошибки в рантайме. Лучше fail at once (или как эта стратегия называется - запамятовал).

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.API/Program.cs
> +				.UseDefaultServiceProvider(options => options.ValidateScopes = false) // for EF core
Написал коммент ниже про миграции. Возможно это решит проблему.

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.API/appsettings.Development.json
> +﻿{
Думаю, dev-конфигурацию не надо добавлять в git.
Придется либо делать каждому 1-в-1 окружение с одинаковыми конфигами, либо каждый раз чертыхаясь переписывать dev.json после вытягивания ветки.

Про остальные конфиг файлы я бы тоже подумал - мы же хотели сделать для них приватную репу.

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.API/SwaggerConfiguration/SwaggerDefaultValues.cs
> +		#pragma warning disable CA1062
Вопрос по IDE, форматированию и данной прагме. Вижу, что во многих файлах отступы переформатированы - затрудняет ревью. 
В чем ты работаешь, какие дефолты выставлены и для чего везде дизеблится данный варнинг?
Не люблю эти директивы для компилятора в явном виде в коде.

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.Domain/Models/Class.cs
> +	public class Class
Я что-то не подумал при составлении схемы БД, что `class Class` будет так стремно выглядеть :)
Может, переименуем сущность в `Lesson`?

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.API/Services/DependencyInjectionServiceExtensions.cs
> +		}
В конфиг следует добавить идентити-менджмент с нашими кастомными классами для юзера и роли, а сами классы унаследовать от `IdentityUser` и `IdentityRole`. При этом некоторые поля, которые уже есть в Identity можно убрать, а кастомный класс `Role` вообще исключить, так как он ничего нового не вносит. 
```
services.AddIdentity<User, Role>()
             .AddEntityFrameworkStores<BrimSceduleContext>();
```

Или не добавлять, если мы планируем менеджить их самостоятельно. Фреймворк предлагает хороший функционал из коробки на случай, если мы захотим добавить различные способы авторизации в будущем.

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.Persistence/EF/BrimScheduleContext.cs
> +			);
Если использовать подход с Identity, как я описал [выше](backend/BrimSchedule.API/Services/DependencyInjectionServiceExtensions.cs), добавлять роли через modelBuilder, возможно, не выйдет. Надо будет рассмотреть доку, как это лучше сделать.

На одном из старых проектов я писал seeder-класс, который заполнян БД init-данными. Вызывался там же, где миграции. Роли добавлялись асинхронно через класс RoleManager фреймворка (синхронно он не умеет). Выглядело громоздко, может сейчас фреймворк варианты получше предлагает.

З.Ы. Раз уж названия ролей вынесены в константы, лучше их вместо строк и подставить.

2021-02-17 11:59 UTC, Demestrus commented on backend/BrimSchedule.Persistence/Repositories/EFUnitOfWork.cs
> +			_db = new BrimScheduleContext(connectionString);
Никогда не любил подход с UnitOfWork, мне он кажется избыточным, но это ИМХО.

Надо как-нибудь созвониться, поболтать, потому что по этому классу у меня несколько вопросов, на которые нужны развернутые ответы :)

Конкретно в данной строчке смущает создание экземпляра контекста через new, а не резолв из DI, где он уже сконфигурирован под npgsql. Вероятно, контекст не сможет без этого общаться с базой.

2021-02-23 11:00 UTC, Silurus commented on backend/BrimSchedule.Persistence/EF/BrimScheduleContext.cs
> +				.ToTable("Users")
Переименовал таблицу из AspNetUsers в Users, то же самое сделал с таблицей Roles

2021-02-23 11:03 UTC, Silurus commented on backend/BrimSchedule.Persistence/Repositories/GenericRepository.cs
> +	public class GenericRepository<TEntity>: IRepository<TEntity>
Сделал один GenericRepository вместо кучи отдельных для UnitOfWork

2021-02-23 11:04 UTC, Silurus commented on backend/BrimSchedule.API/Startup.cs
> +			dbContext.Database.Migrate();
Перенес миграцию в Program.Main() 👍

2021-02-23 17:19 UTC, Demestrus commented on backend/BrimSchedule.Persistence/Repositories/GenericRepository.cs
> +	public class GenericRepository<TEntity>: IRepository<TEntity>
Предлагаю имя просто Repository для лучшей читаемости

2021-02-23 17:39 UTC, Demestrus commented on backend/BrimSchedule.API/SwaggerConfiguration/SwaggerDefaultValues.cs
> +		#pragma warning disable CA1062
По поводу форматирования напиши все-таки)
У меня Rider без дополнительных претифайеров и настроек форматит код, через него проект и создавал.
У тебя Rider? Вот тут у тебя табы стоят?
<img width="983" alt="image" src="https://user-images.githubusercontent.com/32338714/108884025-2dd21480-7617-11eb-8239-23d5d98fa71a.png">

2021-02-23 17:41 UTC, Demestrus approved these changes

2021-02-23 17:50 UTC, Demestrus commented on backend/BrimSchedule.Domain/Models/User.cs
> +		public int RoleId { get; set; }
Во фреймворке автоматически создается табличка AspNetUserRoles, связывающая юзера и роль, правда как N - N, но мне кажется, это даже лучше на будущее. Тут связь стоит убрать.

2021-02-23 18:20 UTC, Silurus commented on backend/BrimSchedule.API/SwaggerConfiguration/SwaggerDefaultValues.cs
> +		#pragma warning disable CA1062
Да, сорян, пропустил вопрос. У меня табы выставлены, размер 1 таба как 4 пробела

2021-02-23 18:20 UTC, Silurus commented on backend/BrimSchedule.API/SwaggerConfiguration/SwaggerDefaultValues.cs
> +		#pragma warning disable CA1062
Имхо табы считать проще

2021-02-23 18:21 UTC, Silurus commented on backend/BrimSchedule.Persistence/Repositories/GenericRepository.cs
> +	public class GenericRepository<TEntity>: IRepository<TEntity>
Понял, поправлю перед мерджем

2021-02-26 14:26 UTC, merged