Users API and infrastructure manipulations
Demestrus/BrimScheduleApp pull request #7
Opened 2021-03-30 19:17 UTC by Demestrus

В соответсвии с https://trello.com/c/iN2haytn
- Добавил API для пользователей 
- Добавил Seeder для добавления админского аккаунта при старте приложения.
- Покрыл Unit-тестами

По ходу дела потянул еще несколько доработок:
- интерфейсы переместил в слой Application, настроил взаимосвязи между проектами в соответствии с "луковой" ахритектурой
- ServiceResult тоже переехал в Application, добавил дженериковую версию для предотвращения боксинга раньше времени, а также статические фабрики SuccessResult и FailureResult
- полностью удалил коробочный Identity из проекта за ненадобностью. Как следствие было удалено наследование от IdentityContext и соответствующие таблички. Поскольку изменения были крупными, а мы пока далеко не продвинулись, решил пересоздать инитовую миграцию, поэтому перед запуском **нужно грохнуть локальную БД целиком**, если она была
- поскольку для тестирования и работы с апи нужны токены авторизации, решил перетянуть в ветку тестовую страничку авторизации. Поддержку MVC контроллеров добавил только для dev'а, поэтому страничка в прод попасть не должна. Пользоваться следующим образом: 
  1. Заходим на страничку, логинимся
  2. Находим указанную строчку в отображенном после логина json и копируем в буфер  
  
  <img src="https://user-images.githubusercontent.com/32338714/113141325-3b8c4280-9232-11eb-9148-594abb3822c5.png" width="400">
  
  3. Заходим в свагер
  4. Клацаем по любому из понравившихся замочков  
  
  <img src="https://user-images.githubusercontent.com/32338714/113141876-f0266400-9232-11eb-9edd-a884167f891e.png" width="500">
  
  5. В поле для ввода токена пишем _"Bearer "_ и вставляем скопированный ранее токен  
  
  <img src="https://user-images.githubusercontent.com/32338714/113142103-34196900-9233-11eb-86a8-2dd8311a64ad.png" width="500">

  6. Клацаем Authorize - готово, вы восхитительны, можно тестить апишку

2021-04-03 19:25 UTC, Silurus commented on backend/BrimSchedule.API/Controllers/AuthTestController.cs
> +	[Authorize]
Есть предложение сделать свой атрибут, например, TestOnlyAttribute. Он будет возвращать 404 в случае Production среды. Мне кажется, это более наглядное решение (сразу видно, что атрибут висит над контроллером, значит контроллер только для тестовой среды), и не даст зафакапиться с конфигурацией

`using System;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace BrimSchedule.API.Services.Authentication
{
	public class TestOnlyAttribute: Attribute, IActionFilter
	{
		public void OnActionExecuting(ActionExecutingContext context)
		{
			var env = context.HttpContext.RequestServices.GetService<IWebHostEnvironment>();
			if (env.IsStaging() || env.IsProduction())
			{
				context.Result = new NotFoundResult();
			}
		}

		public void OnActionExecuted(ActionExecutedContext context)
		{
		}
	}
}
`

2021-04-04 08:39 UTC, Silurus requested changes
![image](https://user-images.githubusercontent.com/19695435/113503380-2c5f0a80-953a-11eb-9d23-88fdea893240.png)

В проектах нужно выровнять nuget пакет для EF Core до 5.0.3.0, а то варнинги при билде есть

2021-04-04 08:39 UTC, Silurus commented on backend/BrimSchedule.API/Startup.cs
> +			services.AddControllersWithViews();
Эту штуку не надо под CurrentEnvironment.IsDevelopment() помещать? Доступ к AuthTestController не открыт сейчас?

2021-04-04 22:01 UTC, Demestrus commented on backend/BrimSchedule.API/Controllers/AuthTestController.cs
> +	[Authorize]
Хорошая мысль!
Вот только мне подумалось, что было бы изящнее не в виде экшн-фильтра сделать, а на уровне конфигурации хоста в Startup. Где-то в UseEndpoints или еще где проверять контроллер на наличие данного атрибута, и если он есть, просто не включать контроллер хост. Пошарю на эту тему, если что-то красивое получится - добавлю, предложу оценить, если нет - возьму твое предложение как есть.

Атрибут я бы, кстати, переименовал в DevOnly, а то название больше на тесты отсылает

2021-04-04 22:07 UTC, Demestrus commented on backend/BrimSchedule.API/Startup.cs
> +			services.AddControllersWithViews();
По идее, достаточно не включать MVC-контроллеры в прод в методе Configure
```csharp
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
		endpoints.MapHealthChecks("/health");

		if (isDevelopment)
		{
			endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
		}
            });
```

Данная строчка просто в DI добавляет нужную шляпу для ControllersWithViews, в принципе можно ее и под isDevelopment загнать, чтобы лишние зависимости не конфигурировались. з
Запуск на пяток микросекунд быстрее будет 😃

2021-04-04 22:09 UTC, Demestrus commented on backend/BrimSchedule.API/Startup.cs
> +			services.AddControllersWithViews();
Про варнинги чет ветка беседы не создалась отдельная. За наводку спасибо! Видел варнинг, но не понял, где что конфликтует и забил. Поправлю.

2021-04-06 10:14 UTC, Demestrus commented on backend/BrimSchedule.API/Controllers/AuthTestController.cs
> +	[Authorize]
Нашел фичу, которая помогла сделать то, что нужно.

```csharp
var mvcBuilder = CurrentEnvironment.IsDevelopment()
	? services.AddControllersWithViews()
	: services.AddControllers();
mvcBuilder.ConfigureApplicationPartManager(
	manager => manager.FeatureProviders.Add(new ExposeInEnvironmentControllerFeatureProvider(CurrentEnvironment))
);
```
Переместил вызов `services.AddControllersWithViews()` поближе к сородичу и добавил условие вызова одного или второго. По сути, WithViews является более широким эстеншеном AddControllers, поэтому смысла вызывать их вместе особо нет. AddRazorPages вообще снес за ненадобностью -  нам не востребовано оказалось.

Далее конфигурируется штука под названием FeatureProvider. Она позволяет производить всякие манипуляции над зарегистрированными контроллерами. Собственно, мы добавляем свой кастомный провайдер, внутри которого отсеиваются контроллеры, обмазанные атрибутом DevOnly, в зависимости от среды выполнения.

Протестил в деве и проде в разных вариациях. Как минимум контроллеры с view не вызваются в проде благодаря тому, что писал [тут](https://github.com/Brim-Schedule-Team/BrimScheduleApp/pull/7#discussion_r606859582), как максимум - любые контроллеры с пометкой DevOnly не будут даже зарегистрированы на проде, поэтому api-контроллеры тоеж можно обмазывать в случае необходимости.

2021-04-06 10:19 UTC, Demestrus commented on backend/BrimSchedule.API/Startup.cs
> +			services.AddControllersWithViews();
Варгнинги пофиксил, правда пришлось даунгрейднуться. Конфликтуют зависимости в пакетах NpgSql и EntityFrameworkTools. У первого максимальная версия - 5.0.2 (далее только превьюха 6.0.0 доступна), у второго - 5.0.4. 
Выставил обе в 5.0.2. Надеюсь, проблемы, решаемые минорными патчиками, нас не коснутся.

2021-04-12 18:44 UTC, Silurus approved these changes

2021-04-13 07:19 UTC, merged